/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StandardTools;

import java.awt.Frame;
import javax.swing.JFileChooser;

/**
 *
 * @author PDI
 */
public class FileDialogBean extends javax.swing.JPanel {

    private int FileSelectionMode;

    /**
     * Get the value of FileSelectionMode
     *
     * @return the value of FileSelectionMode
     */
    public int getFileSelectionMode() {
        return FileSelectionMode;
    }

    /**
     * Set the value of FileSelectionMode
     *
     * @param FileSelectionMode new value of FileSelectionMode
     */
    public void setFileSelectionMode(int FileSelectionMode) {
        this.FileSelectionMode = FileSelectionMode;
    }

    private String InputText="Test Data";

    /**
     * Get the value of InputText
     *
     * @return the value of InputText
     */
    public String getInputText() {
        return InputText;
    }

    /**
     * Set the value of InputText
     *
     * @param InputText new value of InputText
     */
    public void setInputText(String InputText) {
        this.InputText = InputText;
    }
    private String ButtonText="ButtonName";

    /**
     * Get the value of ButtonText
     *
     * @return the value of ButtonText
     */
    public String getButtonText() {
        return ButtonText;
    }

    /**
     * Set the value of ButtonText
     *
     * @param ButtonText new value of ButtonText
     */
    public void setButtonText(String ButtonText) {
        this.ButtonText = ButtonText;
        jButton.setText(ButtonText);
    }

    /**
     * Creates new form FileDialogBean
     */
    public FileDialogBean() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();

        jTextField.setText("---[File Path]----");

        jButton.setText(getButtonText());
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
      
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(FileSelectionMode);
        fc.showOpenDialog(jTextField);
        if(fc.getSelectedFile()!=null)
        jTextField.setText(fc.getSelectedFile().getAbsolutePath());
        else
        jTextField.setText("---No Selection Made---");
        
    }//GEN-LAST:event_jButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton;
    public javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
