/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mk.os;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import json.JSONArray;
import json.JSONException;
import json.JSONObject;
import json.mkJSON;
import net.mk.DTasks.OSAppGetProcessDetail;
import net.mk.ppmcuGUI.MCWConfClass;
import net.mk.ppmcuGUI.FrontPage;
import org.hyperic.sigar.SigarException;

/**
 *
 * @author PDI
 */
public class RunningAppsPanel extends javax.swing.JPanel {

    DefaultTableModel DTM;
    
    public static JSONObject RemoteSysSpec;
    protected String LICENSE_KEY;
    public static boolean REMOTE_DATA = false;
    Object[][] DV;

    /**
     * Creates new form RunningAppsPanel
     */
    public RunningAppsPanel(String WebServerName, String _LICENSE_KEY, JSONObject _RemoteSysSpec) {
        DTM = new DefaultTableModel();
        this.LICENSE_KEY = _LICENSE_KEY;
        this.RemoteSysSpec = _RemoteSysSpec;
        initComponents();
        jTable1.setAutoCreateRowSorter(true);
        DV = new Object[1][1];
         //if (System.getProperty("os.name").toLowerCase().indexOf("windows") > -1) 

             //DV = mkJSON.ConvertToObjectArray(WindowsUtils.RunningProcesses(false));
        Thread t2 = new Thread(new Runnable() {
            public void run() {
                try {

                    while (true) {
                        try {
       // DV = mkJSON.ConvertToObjectArray(new OSApp().getProcesses());

                            if (!MCWConfClass.REMOTE_DATA_MODE) {
                                RemoteSysSpec.put("ALL_PROC", OSApp.getProcesses());
                                 //System.out.println(RemoteSysSpec.toString(1));
                                 //System.out.println(OSApp.getProcesses());
                                DV = mkJSON.ConvertToObjectArray(RemoteSysSpec.getJSONObject("ALL_PROC"), OSApp.ProcessColumns.length);
                            }

                            //To be written for Linux and Mac 5/4/2013
                        } catch (SigarException ex) {
                            Logger.getLogger(RunningAppsPanel.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (JSONException ex) {
                            Logger.getLogger(RunningAppsPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        DTM.setDataVector(DV, OSApp.ProcessColumns);
                        Thread.sleep(5000);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

        t2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(DTM);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) throws SigarException, JSONException {
        
        
//            JSONObject allProcess=OSApp.getProcesses();
//            JSONArray names=allProcess.names();
//            for(int i=0;i<names.length();i++){   //jusched.exe mDNSResponder Dwm
//                if(allProcess.getJSONArray(names.getString(i)).toString().contains("jusched"))
//                   System.out.println(allProcess.getJSONArray(names.getString(i)).toString());
//            }
       
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunningAppsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunningAppsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunningAppsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunningAppsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                JOptionPane.showMessageDialog(null, new RunningAppsPanel("","",new JSONObject()));
            }
        });
        
        
       
    }
    
}
