/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mk.ppmcuGUI;

/**
 *
 * @author PDI
 */
public class AdvancedSetupPanel extends javax.swing.JPanel {
protected String WebServerName="127.0.0.1:8888/multicoreworld";
    /**
     * Creates new form AdvancedSetupPanel
     */
    public AdvancedSetupPanel(String WebServerName) {
        this.WebServerName=WebServerName;
        initComponents();
        USERNAME.setText(System.getProperty("user.name"));
        
        int numberOfPocessor=Runtime.getRuntime().availableProcessors();
        
        if(numberOfPocessor==1){CPU_TYPE.setSelectedIndex(CPU_TYPE.getItemCount()-1);}
        if(numberOfPocessor==2){CPU_TYPE.setSelectedIndex(0);}
        if(numberOfPocessor==4){CPU_TYPE.setSelectedIndex(1);}
        if(numberOfPocessor==8){CPU_TYPE.setSelectedIndex(2);}
        if(numberOfPocessor>8 ){CPU_TYPE.setSelectedIndex(4);}
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Type1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CPU_TYPE = new javax.swing.JComboBox();
        DATA_PUBLIC = new javax.swing.JCheckBox();
        RUN_CLASS_TEST = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        RANK_OUTPUT = new javax.swing.JTextArea();
        SHARE_COMPUTING_POWER = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("User Name:");

        USERNAME.setText("NotGiven");

        jLabel2.setText("Email:");

        EMAIL.setText("NotGiven");

        jLabel3.setText("Account Type:");

        Type1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "PC User",
            "Gamer",
            "Neo",
            "Vendor"}));

jLabel4.setText("This CPU Class:");

CPU_TYPE.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
    "PC",
    "Gaming PC",
    "Monster PC",
    "Gaming Monster",
    "Workstation",
    "CAD Workstation",
    "Cluster",
    "Super Computer",
    "IKeepVintage"}));

    DATA_PUBLIC.setSelected(true);
    DATA_PUBLIC.setText("Make my machine spec and test public");

    RUN_CLASS_TEST.setSelected(true);
    RUN_CLASS_TEST.setText("Run tests based on my CPU Class");

    RANK_OUTPUT.setColumns(20);
    RANK_OUTPUT.setRows(5);
    RANK_OUTPUT.setBorder(null);
    jScrollPane1.setViewportView(RANK_OUTPUT);

    SHARE_COMPUTING_POWER.setSelected(true);
    SHARE_COMPUTING_POWER.setText("Share Computing Power");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(Type1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPU_TYPE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(RUN_CLASS_TEST, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SHARE_COMPUTING_POWER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(3, 3, 3)
            .addComponent(DATA_PUBLIC))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel1)))
            .addGap(15, 15, 15)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3)
                .addComponent(Type1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPU_TYPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(SHARE_COMPUTING_POWER)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RUN_CLASS_TEST)
                .addComponent(DATA_PUBLIC))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox CPU_TYPE;
    public javax.swing.JCheckBox DATA_PUBLIC;
    protected javax.swing.JTextField EMAIL;
    public javax.swing.JTextArea RANK_OUTPUT;
    public javax.swing.JCheckBox RUN_CLASS_TEST;
    private javax.swing.JCheckBox SHARE_COMPUTING_POWER;
    public javax.swing.JComboBox Type1;
    public javax.swing.JTextField USERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
