/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mk.ppmcuGUI;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import json.JSONArray;
import json.JSONException;
import json.mkJSON;

/**
 *
 * @author PDI
 */
public class CPUProfile extends javax.swing.JPanel {

    public String[] list;
    DefaultComboBoxModel models = new DefaultComboBoxModel( new String[]{"A1", "A2"});
    protected String LICENSE_KEY="NOTSET";
    /**
     * Creates new form CPUProfile
     */
    public CPUProfile(String WebServerName) {
        list=new String[]{"General",
            " Purpose",
            "Games",
            " HD-Movies",
            " Music",
            " Multimedia",
            " CAD Desktop",
            " CAD Workstation",
            " Photo Editing",
            " Audio Editing",
            " Movie Editing",
            " Server",
            " HPC (High Performance Computing"};
        try {
            JSONArray PCProfileNames=new JSONArray(new Web().SendPOST("http://"+WebServerName+"/mcst/GetCPUProfile.php", new String []{"LICENSE_KEY","CPU_PROFILES"}, new String[] {LICENSE_KEY,""}, true));
            models = new DefaultComboBoxModel( mkJSON.getStringArrayFromJSONArray(PCProfileNames));
        } catch (JSONException ex) {
            Logger.getLogger(CPUProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
        
        initComponents();
       
    }

    public CPUProfile() {
        list=new String[]{"General",
            " Purpose",
            "Games",
            " HD-Movies",
            " Music",
            " Multimedia",
            " CAD Desktop",
            " CAD Workstation",
            " Photo Editing",
            " Audio Editing",
            " Movie Editing",
            " Server",
            " HPC (High Performance Computing"};
           models = new DefaultComboBoxModel( list);
       
            
        
        
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(models);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Software Profile:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, 0, 315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
