/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mk.ppmcu2D;

import javax.swing.JOptionPane;
import json.JSONObject;

/**
 *
 * @author PDI
 */
public class Curve3DJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Curve3DJPanel
     */
    public Curve3DJPanel() {
        initComponents();
    }
    
     public Curve3DJPanel(String WebServerName,String LicenseKey, JSONObject SysSpec) {
        initComponents();
        curve3DComponent1.Load(1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        curve3DComponent1 = new net.mk.ppmcu2D.Curve3DComponent();
        jButton1 = new javax.swing.JButton();
        CurveType = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(242, 242, 192));

        jButton1.setText("Preview");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CurveType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
            "Curve 1",
            "Curve 2",
            "Curve 3",
            "Bowl",
            "Helix",
            "Spiral",
            "TransformingSpiral",
            "Butterfly curve (Transcendental)"}));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
this.setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(curve3DComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 605, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(CurveType, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CurveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(curve3DComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        curve3DComponent1.Load(CurveType.getSelectedIndex()+1);
        //curve3DComponent1.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CurveType;
    private net.mk.ppmcu2D.Curve3DComponent curve3DComponent1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

public static void main(String Args[]){
    
    JOptionPane.showMessageDialog(null, new Curve3DJPanel());
}
}
