/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.mk.ppmcu2D;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import json.JSONObject;
import net.mk.ppmcuGUI.Web;

/**
 * 4/28/2013 Add Auto rotation to the 2D/3D models
 * @author PDI
 */

public class MultiCore2DPanel extends javax.swing.JPanel {
protected String WebServerName;
String[] modelStrings;
    /**
     * Creates new form MultiCore2DPanel
     */
    public MultiCore2DPanel(String WebServerName,String LicenseKey, JSONObject SysSpec) {
        this.WebServerName=WebServerName;
        modelStrings =new String[] { "MCW","Si-FiCity","Palm-Tree","Dinasaur", "Samurai", "Cube", "Helicopter","Ship"};
        initComponents();
    try {        
        jComponentThreeD1.Load(new URL("http://"+WebServerName+"/Get3DModel.php?LICENSE_KEY=NOTSET&THREEDMODEL="+jComboBox2.getItemAt(3).toString()));
        System.out.println();
    } catch (MalformedURLException ex) {
        Logger.getLogger(MultiCore2DPanel.class.getName()).log(Level.SEVERE, null, ex);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComponentThreeD1 = new net.mk.ppmcu2D.JComponentThreeD();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(242, 242, 192));

        jComponentThreeD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
            modelStrings));
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox2ActionPerformed(evt);
        }
    });

    jLabel1.setText("Select(Download) 3D Model");

    jCheckBox1.setSelected(true);
    jCheckBox1.setText("Multi-Core");
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox1ActionPerformed(evt);
        }
    });

    jCheckBox2.setSelected(true);
    jCheckBox2.setText("Single-Core");
    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jComponentThreeD1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jCheckBox2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComponentThreeD1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jCheckBox1)
                .addComponent(jCheckBox2)))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    try {
        jComponentThreeD1.Load(new URL("http://"+WebServerName+"/Get3DModel.php?LICENSE_KEY=NOTSET&THREEDMODEL="+jComboBox2.getSelectedItem().toString()));
//        jComponentThreeD1.Load(Web.SendPOST("http://"+WebServerName+"/Get3DModel.php",
//                new String[]{"LICENCE_KEY","THREEDMODEL"},
//                new String[]{"NOTSET",jComboBox2.getSelectedItem().toString()},false));
    } catch (MalformedURLException ex) {
        Logger.getLogger(MultiCore2DPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       
        jComponentThreeD1.md.SINGLE_CORE_REGEN=jCheckBox2.isSelected();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        jComponentThreeD1.md.MULTI_CORE_REGEN=jCheckBox1.isSelected();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    public net.mk.ppmcu2D.JComponentThreeD jComponentThreeD1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
